# question_prep.py
# Creates/replaces questions.py from a saved question list.
# Saved lists can be .py or .json files inside question_lists/.
# New question lists are saved as .py files.

from pathlib import Path
import json
import pprint
import runpy

BASE_DIR = Path(__file__).parent
LISTS_DIR = BASE_DIR / "question_lists"
ACTIVE_QUESTIONS_FILE = BASE_DIR / "questions.py"


def load_questions_from_json(path):
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)


def load_questions_from_py(path):
    data = runpy.run_path(str(path))
    if "questions" not in data:
        raise ValueError(f"{path.name} does not contain a variable named questions.")
    return data["questions"]


def save_questions_to_py_file(path, questions, active=False):
    if active:
        header = (
            "# Auto-generated by question_prep.py\n"
            "# Do not edit this file directly unless you want temporary changes.\n\n"
        )
    else:
        header = "# Saved question list created by question_prep.py\n\n"

    text = header
    text += "questions = "
    text += pprint.pformat(questions, width=80, sort_dicts=False)
    text += "\n"

    with open(path, "w", encoding="utf-8") as f:
        f.write(text)


def save_as_active_questions_py(questions):
    save_questions_to_py_file(ACTIVE_QUESTIONS_FILE, questions, active=True)


def list_question_files():
    LISTS_DIR.mkdir(exist_ok=True)

    files = sorted(
        list(LISTS_DIR.glob("*.py")) +
        list(LISTS_DIR.glob("*.json"))
    )

    return [f for f in files if f.name != "__init__.py"]


def choose_existing_file():
    files = list_question_files()

    if not files:
        print("No question files found in question_lists/.")
        return None

    print("\nAvailable question files:\n")
    for i, file in enumerate(files, start=1):
        print(f"{i}. {file.name}")

    choice = input("\nChoose a file number: ").strip()

    try:
        index = int(choice) - 1
        return files[index]
    except (ValueError, IndexError):
        print("Invalid choice.")
        return None


def create_new_py_file():
    LISTS_DIR.mkdir(exist_ok=True)

    filename = input("New question list name, without extension: ").strip()

    if not filename:
        print("No filename entered.")
        return

    if not filename.startswith("questions_"):
        filename = "questions_" + filename

    path = LISTS_DIR / f"{filename}.py"

    if path.exists():
        overwrite = input(f"{path.name} already exists. Replace it? y/n: ").strip().lower()
        if overwrite != "y":
            print("Canceled.")
            return

    default_category = input("Category for this list, example coding.history: ").strip()

    if not default_category:
        default_category = "general"

    questions = []

    print("\nEnter questions. Leave the prompt blank when finished.\n")

    while True:
        prompt = input("Prompt: ").strip()

        if not prompt:
            break

        answer_a = input("A: ").strip()
        answer_b = input("B: ").strip()
        answer_c = input("C: ").strip()
        answer_d = input("D: ").strip()

        correct_answer = input("Correct answer A/B/C/D: ").strip().upper()

        while correct_answer not in ["A", "B", "C", "D"]:
            print("Please enter A, B, C, or D.")
            correct_answer = input("Correct answer A/B/C/D: ").strip().upper()

        questions.append({
            "category": default_category,
            "prompt": prompt,
            "answers": {
                "A": answer_a,
                "B": answer_b,
                "C": answer_c,
                "D": answer_d,
            },
            "correct_answer": correct_answer,
        })

        print("Added.\n")

    if not questions:
        print("No questions entered. Nothing saved.")
        return

    save_questions_to_py_file(path, questions)
    print(f"\nSaved: {path}")

    save_now = input("Make this the active questions.py now? y/n: ").strip().lower()

    if save_now == "y":
        save_as_active_questions_py(questions)
        print("questions.py has been replaced.")


def use_existing_file():
    path = choose_existing_file()

    if path is None:
        return

    if path.suffix == ".json":
        questions = load_questions_from_json(path)
    elif path.suffix == ".py":
        questions = load_questions_from_py(path)
    else:
        print("Unsupported file type.")
        return

    save_as_active_questions_py(questions)
    print(f"\nquestions.py has been replaced using: {path.name}")


def show_menu():
    print("\n==============================")
    print("QUESTION PREP")
    print("==============================")
    print("1. Use an existing question file")
    print("2. Create a new Python question file")
    print("3. Quit")


def main():
    while True:
        show_menu()
        choice = input("\nChoose 1, 2, or 3: ").strip()

        if choice == "1":
            use_existing_file()
        elif choice == "2":
            create_new_py_file()
        elif choice == "3":
            print("Goodbye.")
            break
        else:
            print("Invalid choice.")


if __name__ == "__main__":
    main()